// mzgen extracts the pieces of the misterzine website that the device app must
// mirror exactly: the CORE_NAMES and SRC_NAMES literals from
// docs/releases/index.html and the "eva" (Unit-01) palette block from
// docs/theme.css. It writes Go source into internal/gen. Run it whenever the
// site changes those tables:
//
//	go run ./cmd/mzgen -site ../misterzine -out internal/gen
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

func main() {
	site := flag.String("site", "../misterzine", "path to the misterzine site checkout")
	out := flag.String("out", "internal/gen", "output directory")
	flag.Parse()

	html, err := os.ReadFile(filepath.Join(*site, "docs", "releases", "index.html"))
	die(err)
	css, err := os.ReadFile(filepath.Join(*site, "docs", "theme.css"))
	die(err)

	coreNames := jsObject(string(html), "const CORE_NAMES = {")
	srcNames := jsObject(string(html), "const SRC_NAMES = {")
	if len(coreNames) < 50 || len(srcNames) < 4 {
		die(fmt.Errorf("extraction looks wrong: %d core names, %d src names", len(coreNames), len(srcNames)))
	}
	tokens := cssBlock(string(css), `:root[data-theme="eva"] {`)
	if len(tokens) < 10 {
		die(fmt.Errorf("eva palette block not found or too small (%d tokens)", len(tokens)))
	}

	die(writeGo(filepath.Join(*out, "names.go"), namesSource(coreNames, srcNames)))
	die(writeGo(filepath.Join(*out, "palette.go"), paletteSource(tokens)))
	fmt.Printf("mzgen: %d core names, %d src names, %d palette tokens\n", len(coreNames), len(srcNames), len(tokens))
}

func die(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "mzgen:", err)
		os.Exit(1)
	}
}

// jsObject returns the key/value pairs of a JS object literal that starts at
// marker and ends at the first "};" line. Keys may be quoted or bare; values
// may be single- or double-quoted. Line comments are stripped first.
func jsObject(src, marker string) map[string]string {
	i := strings.Index(src, marker)
	if i < 0 {
		die(fmt.Errorf("marker %q not found", marker))
	}
	rest := src[i+len(marker):]
	j := strings.Index(rest, "\n};")
	if j < 0 {
		die(fmt.Errorf("end of %q not found", marker))
	}
	body := rest[:j]
	var lines []string
	for _, ln := range strings.Split(body, "\n") {
		if k := strings.Index(ln, "//"); k >= 0 {
			ln = ln[:k]
		}
		lines = append(lines, ln)
	}
	body = strings.Join(lines, "\n")
	re := regexp.MustCompile(`(?:'((?:[^'\\]|\\.)*)'|([A-Za-z_][A-Za-z0-9_]*))\s*:\s*(?:'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)")`)
	m := map[string]string{}
	for _, g := range re.FindAllStringSubmatch(body, -1) {
		key := g[1]
		if key == "" {
			key = g[2]
		}
		val := g[3]
		if g[3] == "" && g[4] != "" {
			val = g[4]
		}
		m[unescape(key)] = unescape(val)
	}
	return m
}

func unescape(s string) string {
	s = strings.ReplaceAll(s, `\'`, `'`)
	s = strings.ReplaceAll(s, `\"`, `"`)
	s = strings.ReplaceAll(s, `\\`, `\`)
	return s
}

// cssBlock returns the --token: #hex declarations inside the block that starts
// at marker and ends at the next "}".
func cssBlock(src, marker string) map[string]string {
	i := strings.Index(src, marker)
	if i < 0 {
		die(fmt.Errorf("marker %q not found", marker))
	}
	rest := src[i+len(marker):]
	j := strings.Index(rest, "}")
	body := rest[:j]
	body = regexp.MustCompile(`(?s)/\*.*?\*/`).ReplaceAllString(body, "")
	re := regexp.MustCompile(`--([a-z0-9-]+)\s*:\s*(#[0-9a-fA-F]{3,8})\s*;`)
	m := map[string]string{}
	for _, g := range re.FindAllStringSubmatch(body, -1) {
		m[g[1]] = strings.ToLower(g[2])
	}
	return m
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func namesSource(core, src map[string]string) string {
	var b bytes.Buffer
	b.WriteString("// Code generated by mzgen from the misterzine site; DO NOT EDIT.\n\npackage gen\n\n")
	b.WriteString("// CoreNames mirrors CORE_NAMES in docs/releases/index.html: rbf name to the\n// hardware family label shown as the core label.\n")
	b.WriteString("var CoreNames = map[string]string{\n")
	for _, k := range sortedKeys(core) {
		fmt.Fprintf(&b, "\t%q: %q,\n", k, core[k])
	}
	b.WriteString("}\n\n// SrcNames mirrors SRC_NAMES: pipeline source id to display name.\nvar SrcNames = map[string]string{\n")
	for _, k := range sortedKeys(src) {
		fmt.Fprintf(&b, "\t%q: %q,\n", k, src[k])
	}
	b.WriteString("}\n")
	return b.String()
}

// paletteFields maps struct fields to theme.css tokens. Required ones abort
// the generator when missing so the UI never silently paints black.
var paletteFields = []struct {
	field, token string
	required     bool
}{
	{"Bg", "bg", true}, {"Surface", "surface", true}, {"Fg", "fg", true}, {"Muted", "muted", true},
	{"Line", "line", true}, {"Accent", "accent", true}, {"AccentOn", "accent-on", true},
	{"TypeArcade", "type-arcade", true}, {"TypeConsole", "type-console", true},
	{"TypeComputer", "type-computer", true}, {"TypeOther", "type-other", true},
	{"Ok", "ok", true}, {"Warn", "warn", true}, {"Danger", "danger", true},
	{"BrandHover", "brand-hover", false}, {"Reset", "reset", false}, {"Accent2", "accent2", false},
}

func paletteSource(tokens map[string]string) string {
	var b bytes.Buffer
	b.WriteString("// Code generated by mzgen from the misterzine site; DO NOT EDIT.\n\npackage gen\n\nimport \"image/color\"\n\n")
	b.WriteString("// Theme is one site palette. Fields follow the token names in docs/theme.css.\n")
	b.WriteString("type Theme struct {\n")
	for _, f := range paletteFields {
		fmt.Fprintf(&b, "\t%s color.RGBA\n", f.field)
	}
	b.WriteString("}\n\n// Eva is the site's \"eva\" (Unit-01) theme, the device app's v1 palette.\nvar Eva = Theme{\n")
	for _, f := range paletteFields {
		hex, ok := tokens[f.token]
		if !ok {
			if f.required {
				die(fmt.Errorf("eva palette is missing required token --%s", f.token))
			}
			continue
		}
		r, g, bl, a := parseHex(hex)
		fmt.Fprintf(&b, "\t%s: color.RGBA{%d, %d, %d, %d}, // --%s %s\n", f.field, r, g, bl, a, f.token, hex)
	}
	b.WriteString("}\n\n// EvaTokens holds every colour token of the eva block by its CSS name.\nvar EvaTokens = map[string]color.RGBA{\n")
	for _, k := range sortedKeys(tokens) {
		r, g, bl, a := parseHex(tokens[k])
		fmt.Fprintf(&b, "\t%q: {%d, %d, %d, %d},\n", k, r, g, bl, a)
	}
	b.WriteString("}\n")
	return b.String()
}

func parseHex(h string) (r, g, b, a int) {
	h = strings.TrimPrefix(h, "#")
	var v [4]int
	switch len(h) {
	case 3, 4:
		for i := 0; i < len(h); i++ {
			n := hexVal(h[i])
			v[i] = n*16 + n
		}
		if len(h) == 3 {
			v[3] = 255
		}
	case 6, 8:
		for i := 0; i < len(h)/2; i++ {
			v[i] = hexVal(h[2*i])*16 + hexVal(h[2*i+1])
		}
		if len(h) == 6 {
			v[3] = 255
		}
	default:
		die(fmt.Errorf("bad hex colour %q", h))
	}
	return v[0], v[1], v[2], v[3]
}

func hexVal(c byte) int {
	switch {
	case c >= '0' && c <= '9':
		return int(c - '0')
	case c >= 'a' && c <= 'f':
		return int(c-'a') + 10
	case c >= 'A' && c <= 'F':
		return int(c-'A') + 10
	}
	die(fmt.Errorf("bad hex digit %q", c))
	return 0
}

func writeGo(path, src string) error {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return fmt.Errorf("%s: %w\n%s", path, err, src)
	}
	return os.WriteFile(path, formatted, 0644)
}
