"""Generate the screensaver's letter polygons from a font.

    python tools/saver_letters.py Figtree[wght].ttf 900 > internal/app/saver_letters.go

Instances the variable font at the given weight, flattens each glyph's
outlines for the letters of MISTERZINE into straight segments and writes them
as Go point lists in font units, y down from the top of the cap height. The
largest contour of a glyph is its outline; the rest are counters. The font
itself is not shipped, only these tables.
"""
import sys
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools.pens.basePen import BasePen

path, weight = sys.argv[1], float(sys.argv[2])
font = TTFont(path)
if "fvar" in font:
    font = instancer.instantiateVariableFont(font, {"wght": weight})
cap = font["OS/2"].sCapHeight
glyphs = font.getGlyphSet()
cmap = font.getBestCmap()
name = font["name"].getDebugName(16) or font["name"].getDebugName(1)

class Flatten(BasePen):
    def __init__(self):
        super().__init__(glyphs)
        self.contours, self.cur = [], []
    def _moveTo(self, p):
        self.cur = [p]
    def _lineTo(self, p):
        self.cur.append(p)
    def _curve(self, pts, f):
        p0 = self.cur[-1]
        for i in range(1, 13):
            self.cur.append(f(p0, pts, i / 12))
    def _curveToOne(self, c1, c2, p):
        def cubic(p0, pts, t):
            (x1, y1), (x2, y2), (x3, y3) = pts
            u = 1 - t
            return (u*u*u*p0[0] + 3*u*u*t*x1 + 3*u*t*t*x2 + t*t*t*x3,
                    u*u*u*p0[1] + 3*u*u*t*y1 + 3*u*t*t*y2 + t*t*t*y3)
        self._curve((c1, c2, p), cubic)
    def _qCurveToOne(self, c, p):
        def quad(p0, pts, t):
            (x1, y1), (x2, y2) = pts
            u = 1 - t
            return (u*u*p0[0] + 2*u*t*x1 + t*t*x2, u*u*p0[1] + 2*u*t*y1 + t*t*y2)
        self._curve((c, p), quad)
    def _closePath(self):
        if len(self.cur) > 2:
            if self.cur[0] == self.cur[-1]:
                self.cur.pop()
            self.contours.append(self.cur)
        self.cur = []
    def _endPath(self):
        self._closePath()

def area(c):
    return sum(x0*y1 - x1*y0 for (x0, y0), (x1, y1) in zip(c, c[1:] + c[:1])) / 2

def pts(c):
    return "[]image.Point{" + ", ".join("{%d, %d}" % (round(x), round(cap - y)) for x, y in c) + "}"

out = ["// Code generated by tools/saver_letters.py from %s at weight %d; DO NOT EDIT." % (name, weight), "",
       "package app", "", 'import "image"', "",
       "// saverUnits is the cap height of the source font in its own units; letter",
       "// coordinates run in those units, y down from the top of the capitals.",
       "const saverUnits = %d" % cap, "",
       "var saverLetters = map[byte]saverLetter{"]
for ch in sorted(set("MISTERZINE")):
    g = cmap[ord(ch)]
    pen = Flatten()
    glyphs[g].draw(pen)
    contours = sorted(pen.contours, key=lambda c: -abs(area(c)))
    counters = ", ".join(pts(c) for c in contours[1:])
    out.append("\t'%s': {%d, %s, %s}," % (ch, glyphs[g].width, pts(contours[0]),
                                         "[][]image.Point{" + counters + "}" if counters else "nil"))
out += ["}", ""]
sys.stdout.write("\n".join(out))
