"""Derive the taller list title font from scientifica.

scientifica-11 has 7 px capitals and a 5 px x-height; Spleen 6x12, the body
font, has 8 and 6. This makes every glyph one pixel taller inside the
x-height band so capitals, ascenders and lowercase all match the body font's
proportions: the band row with the fewest lit pixels (a vertical stroke
rather than a crossbar, nearest the middle on ties) is duplicated and the
rows above it move up by one. The descenders and the baseline stay put.

    python tools/tall_font.py internal/fonts/scientifica-11.bdf internal/fonts/scientifica-11-tall.bdf

Every glyph is written as a full 5x12 cell (BBX 5 12 0 -2). OVERRIDES
replaces the x-height band of glyphs the rule serves badly.
"""
import re
import sys
from pathlib import Path

src, dst = Path(sys.argv[1]), Path(sys.argv[2])
text = src.read_text()
head, rest = text.split("ENDPROPERTIES\n", 1)
fb = re.search(r"FONTBOUNDINGBOX (\d+) (\d+) (-?\d+) (-?\d+)", head)
W, H, descent = int(fb.group(1)), int(fb.group(2)), -int(fb.group(4))
assert (W, H, descent) == (5, 12, 2), fb.group(0)
baseline = H - descent - 1
band = range(baseline - 4, baseline + 1)  # the x-height rows
# hand-set x-height bands (six rows, baseline last), where duplicating a
# row put a crossbar in the wrong place
OVERRIDES = {
    "s": [".###.", "#....", ".##..", "...#.", "...#.", "###.."],
}
head = head.replace("FONT_ASCENT 9", "FONT_ASCENT 10")
head = re.sub(r"^FONT (.*)$", lambda m: "FONT " + m.group(1).replace("scientifica", "scientifica-tall"), head, flags=re.M)
head = head.replace('FAMILY_NAME "scientifica"', 'FAMILY_NAME "scientifica-tall"')
head = head.replace('FONT_NAME "scientifica"', 'FONT_NAME "scientifica-tall"')
head = head.replace('FACE_NAME "scientifica"', 'FACE_NAME "scientifica-tall"')
head = head.replace("COMMENT \"Generated by fontforge, http://fontforge.sourceforge.net\"",
                    "COMMENT \"Derived from scientifica-11 by tools/tall_font.py: one row taller in the x-height band\"")

out = []
for glyph in re.findall(r"STARTCHAR .*?ENDCHAR\n", rest, re.S):
    m = re.search(r"BBX (\d+) (\d+) (-?\d+) (-?\d+)\nBITMAP\n(.*?)ENDCHAR", glyph, re.S)
    bbw, bbh, bbx, bby = map(int, m.group(1, 2, 3, 4))
    rows = [int(r, 16) for r in m.group(5).split()]
    cell = [0] * H
    top = H - descent - bby - bbh
    for i, r in enumerate(rows):
        y = top + i
        if 0 <= y < H:
            cell[y] = (r >> bbx) if bbx >= 0 else ((r << -bbx) & 0xFF)
    assert cell[0] == 0, ("glyph uses the top row", glyph[:30])
    name = re.match(r"STARTCHAR (\S+)", glyph).group(1)
    if name in OVERRIDES:
        rows6 = [int(r.replace(".", "0").replace("#", "1"), 2) << (8 - W) for r in OVERRIDES[name]]
        cell = cell[1:baseline - 4] + rows6 + cell[baseline + 1:]
        assert len(cell) == H
    elif any(cell):
        pick = min(band, key=lambda y: (bin(cell[y]).count("1"), abs(y - (baseline - 2)), y))
        cell = cell[1:pick + 1] + [cell[pick]] + cell[pick + 1:]
        assert len(cell) == H
    body = "".join("%02X\n" % r for r in cell)
    glyph = re.sub(r"BBX .*?\nBITMAP\n.*?ENDCHAR", "BBX %d %d 0 %d\nBITMAP\n%sENDCHAR" % (W, H, -descent, body), glyph, flags=re.S)
    out.append(glyph)
dst.write_text(head + "ENDPROPERTIES\n" + rest.split("\n", 1)[0] + "\n" + "".join(out) + "ENDFONT\n", newline="\n")
print("wrote", dst, len(out), "glyphs")
